### ISSUE TITLE
Refactoring suggestion

### ISSUE THREAD

**Issue by jmfayard** [jitinsharma/Kotlin.someExtensions#2]
Hello,

you may want to have a look at my article on how to scope extension functions inside an object
https://dev.to/jmfayard/with-configobject-language-kotlin-issparkingjoy-ic4

This way extensions functions that are not needed don't pollute all the codebase. It would then make sense to publish your extensions as Gradle dependencies instead of the workflow being "hey, just copy paste all the things!".

Just a suggestion, obviously you do whatever you prefer.

**Comment by jitinsharma** [comment]
The idea seems good but for now I don't plan to publish library out of these extensions, these are mostly on copy-paste basis as they serve generic purposes.
